export const TOGGLE_INCIDENT_PANEL = 'TOGGLE_INCIDENT_PANEL';
export const ADD_INCIDENTS = 'ADD_INCIDENTS';
export const CLEAR_INCIDENTS = 'CLEAR_INCIDENTS';
export const MAP_CHANGE = 'MAP_CHANGE';

export const FIELD = 'STRING';
export const SET_ACTIVE_MARKER = 'SET_ACTIVE_MARKER';

export const DESELECT_ALL = 'DESELECT_ALL';
export const SELECT_MULTIPLE = 'SELECT_MULTIPLE';

export const TOGGLE_INCIDENT_FILTER = 'TOGGLE_INCIDENT_FILTER';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const TOGGLE_FILTER_PANEL = 'TOGGLE_FILTER_PANEL';
